apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clockservers.example-solution.metalk8s.scality.com
spec:
  group: example-solution.metalk8s.scality.com
  names:
    kind: ClockServer
    listKind: ClockServerList
    plural: clockservers
    singular: clockserver
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClockServer is the Schema for the clockservers API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClockServerSpec defines the desired state of ClockServer
            properties:
              timezone:
                description: Timezone for this clock, in the format UTC[+/-]HH:MM
                type: string
              version:
                description: The version of the container image to run
                type: string
            required:
            - timezone
            - version
            type: object
          status:
            description: ClockServerStatus defines the observed state of ClockServer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
