---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metalk8s-solution-example.scality.com
  resources:
  - clockservers
  - versionservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metalk8s-solution-example.scality.com
  resources:
  - clockservers/finalizers
  - versionservers/finalizers
  verbs:
  - update
- apiGroups:
  - metalk8s-solution-example.scality.com
  resources:
  - clockservers/status
  - versionservers/status
  verbs:
  - get
  - patch
  - update
