apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-solution-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: example-solution-operator
  template:
    metadata:
      labels:
        name: example-solution-operator
    spec:
      serviceAccountName: example-solution-operator
      containers:
        - name: example-solution-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - example-solution-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "example-solution-operator"
