apiVersion: metalk8s-solution-example.scality.com/v1alpha1
kind: ClockServer
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: clockserver-sample
spec:
  # TODO(user): Add fields here
