name: "Pre Merge"

on:
  workflow_dispatch:

  pull_request:
    branches:
      - "main"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  generate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: operator/go.mod
          cache-dependency-path: operator/go.sum
      - name: Run code generation
        working-directory: operator
        # We run code generation to ensure that the generated code is up to date
        run: |
          go generate ./... &&
          make generate manifests &&
          git diff --quiet

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: operator/go.mod
          cache-dependency-path: operator/go.sum
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          working-directory: operator
